

Latent Dirichlet Allocation (LDA) es un modelo generativo que permite que conjuntos de observaciones puedan ser explicados por grupos no observados que explican por qué algunas partes de los datos son similares. Por ejemplo, si las observaciones son palabras en documentos, presupone que cada documento es una mezcla de un pequeño número de categorías (también denominados como tópicos) y la aparición de cada palabra en un documento se debe a una de las categorías a las que el documento pertenece. LDA es un ejemplo de modelo de categorías




Cargamos los datos de los tickets de dcip

In [21]:
import sys
import IPython
import numpy as np
import pandas as pd
import sklearn as sk


import warnings
warnings.filterwarnings('ignore')
import pandas as pd

df = pd.read_csv("datasets/tickets.csv")

print(df.shape)
df.head(4)

(1070, 2)


subject  \
0             jenkins dejado funcionar   
1  usuario para artefactos artifactory   
2               permisos carpetas dcip   
3                     repo artifactory   

                                             content  
0  partir horas dejado funcionar sospecha causas ...  
1  necesito artifact estamos generando departamen...  
2  podriais permisos carpetas eleven paths dcip 1...  
3  repositorio artifactory para guardar imagenes ...

## Hacemos el preprocesado ##
 - Quitamos las stop words
 - Vectorizamos el texto 

In [ ]:
!pip install stop-words

In [1]:
from stop_words import get_stop_words
stop  = get_stop_words('spanish')
print(stop)

['a', 'al', 'algo', 'algunas', 'algunos', 'ante', 'antes', 'como', 'con', 'contra', 'cual', 'cuando', 'de', 'del', 'desde', 'donde', 'durante', 'e', 'el', 'ella', 'ellas', 'ellos', 'en', 'entre', 'era', 'erais', 'eran', 'eras', 'eres', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'estaba', 'estabais', 'estaban', 'estabas', 'estad', 'estada', 'estadas', 'estado', 'estados', 'estamos', 'estando', 'estar', 'estaremos', 'estará', 'estarán', 'estarás', 'estaré', 'estaréis', 'estaría', 'estaríais', 'estaríamos', 'estarían', 'estarías', 'estas', 'este', 'estemos', 'esto', 'estos', 'estoy', 'estuve', 'estuviera', 'estuvierais', 'estuvieran', 'estuvieras', 'estuvieron', 'estuviese', 'estuvieseis', 'estuviesen', 'estuvieses', 'estuvimos', 'estuviste', 'estuvisteis', 'estuviéramos', 'estuviésemos', 'estuvo', 'está', 'estábamos', 'estáis', 'están', 'estás', 'esté', 'estéis', 'estén', 'estés', 'fue', 'fuera', 'fuerais', 'fueran', 'fueras', 'fueron', 'fuese', 'fueseis', 'fuesen', 'fueses', 'fu

In [30]:
import pandas as pd
NUM_TICKETS=1000
# Cargamos DF
df = pd.read_csv("datasets/tickets.csv")
df = df.head(NUM_TICKETS)
# Quitamos los campos vacios
df['subject'].fillna('', inplace=True)
df['content'].fillna('', inplace=True)
# Un solo campo concatenando Subject + Content
df["ticket"] = df['content'] + df['subject']
# Borrar columnas
del df['content'] 
del df['subject']

df.head(4)


ticket
0  partir horas dejado funcionar sospecha causas ...
1  necesito artifact estamos generando departamen...
2  podriais permisos carpetas eleven paths dcip 1...
3  repositorio artifactory para guardar imagenes ...

In [48]:
# CountVectorizer implements both tokenization and occurrence counting
#  in a single class:
MAX_FEATURES=76

from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer( max_df=.1,max_features=MAX_FEATURES,stop_words=stop,ngram_range=(1, 3))
X = count.fit_transform(df['ticket'].values)
print(count)
print(X.toarray()  , X.shape , X[0].shape  )

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.1, max_features=76, min_df=1,
        ngram_range=(1, 3), preprocessor=None,
        stop_words=['a', 'al', 'algo', 'algunas', 'algunos', 'ante', 'antes', 'como', 'con', 'contra', 'cual', 'cuando', 'de', 'del', 'desde', 'donde', 'durante', 'e', 'el', 'ella', 'ellas', 'ellos', 'en', 'entre', 'era', 'erais', 'eran', 'eras', 'eres', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'e...osotras', 'vosotros', 'vuestra', 'vuestras', 'vuestro', 'vuestros', 'y', 'ya', 'yo', 'él', 'éramos'],
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 0]] (1000, 76) (1, 76)


In [49]:
print(count.get_feature_names())



['acceder', 'access', 'amd64', 'analytics', 'android', 'attached', 'aubay', 'ayuda', 'built', 'cligitapiimpl', 'command', 'configuracion', 'contacta', 'contint', 'contraseña', 'crear', 'david', 'delivery', 'direccion', 'documento', 'ejecucion', 'entorno', 'esclavo', 'export', 'hace', 'help', 'hotfix', 'hotfix built', 'hudson', 'imagen', 'iplanet', 'iplanet messaging', 'iplanet messaging server', 'ituser', 'java', 'java hudson', 'jenkins dcip', 'jenkinsci', 'jira', 'marcossuarez', 'messaging', 'messaging server', 'messaging server hotfix', 'necesito', 'network', 'openstack', 'origin', 'parece', 'plugin', 'plugins', 'problem', 'prodepgdcipm01', 'pruebas', 'pull', 'puppet', 'received', 'release', 'remote', 'repositorio', 'returned', 'script', 'server hotfix', 'server hotfix built', 'setting', 'slave', 'smtp', 'soporte', 'space', 'system', 'tefdigital', 'tener', 'test', 'utf8', 'view', 'wikis', 'workspace']


Sacamos los tópicos de cada ticket

In [34]:
from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_topics=5,
                                random_state=123,
                                learning_method='batch')
X_topics = lda.fit_transform(X)

In [35]:
n_top_words = 6
feature_names = count.get_feature_names()

for topic_idx, topic in enumerate(lda.components_):
    print("Topic %d:" % (topic_idx + 1))
    print(" ".join([feature_names[i]
                    for i in topic.argsort()\
                        [:-n_top_words - 1:-1]]))

Topic 1:
received messaging prodepgdcipm01 smtp analytics hotfix
Topic 2:
esclavo access imagen aubay documento slave
Topic 3:
plugin script contint repositorio david crear
Topic 4:
ituser openstack jira system attached help
Topic 5:
java hudson plugins jenkinsci java hudson amd64


In [38]:

mytopic = X_topics[:, 4].argsort()[::-1]
print ("Caso", mytopic)
for iter_idx, movie_idx in enumerate(mytopic[:8]):
    print('\nTopic #%d:' % (iter_idx + 1))
    print(df['ticket'][movie_idx][:300], '...')
    #print(df['content'][movie_idx][:300], '...')
    


Caso [223 224 220 221 222 429 501 502 508 509 415 187 150 702 105 722   6 552
 728 397 458 445  92 868 662  15 197 611  93 792 168 731 776 178 971 844
  23 633 930 442 327 157 478 100 164 840 616 780 725 680  11 305 755 369
 864 691 614 171 243 645 855 856  58 414 807 587 719 720 698 638 697 639
  89 283  76 906 337 405 929 843 230 232 231 706 121 845 285 229 115 114
 113 287 228 817 108 107 227 102 469 111 718 122 263 730 139 140 141 143
 144 145 268 147 148 262 815 260 256 255 526 160 166 528 540 172 174 137
 542 136 784 125 233 127 481 713 128 714 715 129 716 130 132 717 796 544
 133 271 134 135 786 727 288 126 696 649 366 367 368 371 955 372  21 374
 375 376 640 380 381 314  24 383 941 641 612 311 307 933 182  14 364 964
 981 997 995 993 343   2 210   4 346 983 348 349 363 978 350 351 352 636
 973 972 637 354 362 213 605 591 446 300 432 299 217 298  68 883 882 297
  77  80 579  81 870 866  86 863 690  90 692 854 225 214 678 422 673 215
 588 191 659 304 669 671 421 585 301 175  49 6

In [39]:
# Use tf-idf features for NMF.

from time import time
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import NMF, LatentDirichletAllocation

n_samples = 5000
n_features = 1000
n_components = 10
n_top_words = 20

data_samples = df.content[:n_samples]


def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()



print("Extracting tf-idf features for NMF...")
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2,
                                   max_features=n_features,
                                   stop_words='english')
t0 = time()
tfidf = tfidf_vectorizer.fit_transform(df['content'])
print("done in %0.3fs." % (time() - t0))

# Use tf (raw term count) features for LDA.
print("Extracting tf features for LDA...")
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2,
                                max_features=n_features,
                                stop_words='english')
t0 = time()
tf = tf_vectorizer.fit_transform(data_samples)
print("done in %0.3fs." % (time() - t0))
print()



# Fit the NMF model
print("Fitting the NMF model (Frobenius norm) with tf-idf features, "
      "n_samples=%d and n_features=%d..."
      % (n_samples, n_features))
t0 = time()
nmf = NMF(n_components=n_components, random_state=1,
          alpha=.1, l1_ratio=.5).fit(tfidf)
print("done in %0.3fs." % (time() - t0))

print("\nTopics in NMF model (Frobenius norm):")
tfidf_feature_names = tfidf_vectorizer.get_feature_names()
print_top_words(nmf, tfidf_feature_names, n_top_words)



# Fit the NMF model
print("Fitting the NMF model (generalized Kullback-Leibler divergence) with "
      "tf-idf features, n_samples=%d and n_features=%d..."
      % (n_samples, n_features))
t0 = time()
nmf = NMF(n_components=n_components, random_state=1,
          beta_loss='kullback-leibler', solver='mu', max_iter=1000, alpha=.1,
          l1_ratio=.5).fit(tfidf)
print("done in %0.3fs." % (time() - t0))

print("\nTopics in NMF model (generalized Kullback-Leibler divergence):")
tfidf_feature_names = tfidf_vectorizer.get_feature_names()
print_top_words(nmf, tfidf_feature_names, n_top_words)

print("Fitting LDA models with tf features, "
      "n_samples=%d and n_features=%d..."
      % (n_samples, n_features))
lda = LatentDirichletAllocation(n_components=n_components, max_iter=5,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)
t0 = time()
lda.fit(tf)
print("done in %0.3fs." % (time() - t0))

print("\nTopics in LDA model:")
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

AttributeError: 'DataFrame' object has no attribute 'content'